import Head from 'next/head';
import Image from 'next/image';
import GlobalStyle from '../../styles/globalStyle';
import Background from './bg-pattern-card.svg';
import profileImg from './image-victor.jpg';
import { Container } from '../../styles/profile';

export default function profileCard() {
  return (
    <>
      <Head>
        <title>Profile Card</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;700&display=swap" rel="stylesheet" />
      </Head>
      <GlobalStyle/>
      <Container>
        <div className='profile-card-wrapper'>
          <Image className='background' alt='' src={Background} />
          <div className='profile'>
            <Image className='image-profile' alt='' src={profileImg} />
            <div className='profile-name-age-city'>
              <div className='name-age'>
                <h2>Victor Crest</h2>
                <p>26</p>
              </div>
              <h3>London</h3>
            </div>
            <div className='hr' />
            <div className='socialnetworks'>
              <div className='followers'>
                <h3>80K</h3>
                <p>Followers</p>
              </div>
              <div className='likes'>
                <h3>803K</h3>
                <p>Likes</p>
              </div>
              <div className='photos'>
                <h3>1.4K</h3>
                <p>Photos</p>
              </div>
            </div>
          </div>
        </div>
      </Container>
    </>
  )
}
